name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to publish
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        ref: ${{ github.event.release.tag_name || inputs.tag }}
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD_OPENKIM }}
        skip-existing: true
  send-pull-request-to-kdp:
    uses: openkim/reusable-workflows/.github/workflows/upversion-pypi-package-and-send-pr.yml@main
    secrets: inherit
    with:
      target-repository: developer-platform
      target-repository-base-branch: main
      recipe-file-path: docker/install/Dockerfile
    needs: deploy
